### T-2 Syllabus
- Unit 4 - REGRESSION MODELS 10 MARKS
-  Unit 5 - CLASSIFICATION MODELS 12 MARKS
- Unit 6 - INTRO TO DEEP LEARNING 3 MARKS 

### Unit 4 REGRESSION MODEL

### Three methods to analyze regression techniques
- Manual method
- MS excel based method
- Python based method

### Python based method'

### Linear reg applies to numerical values

### Step 1
- Import libraries

In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

### Step 2: - Import dataset

In [12]:
x=np.array([60,62,67,70,71,72,75,78]).reshape(-1,1)
print(x)


[[60]
 [62]
 [67]
 [70]
 [71]
 [72]
 [75]
 [78]]


In [14]:
y=np.array([140,155,159,179,192,200,212,215])
print(y)

[140 155 159 179 192 200 212 215]


### Step 3: Create a model

In [15]:
model = LinearRegression()

### Step 4: Fit the model


In [16]:
model.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


### Step 5: Print the slope and intercept

In [17]:
#slope
print(model.coef_[0])
#intercept
print(model.intercept_)

4.405495026054004
-124.1312174324965


In [19]:
slope = model.coef_[0]
intercept = model.intercept_

In [28]:
print(f'The linear regression equation is y = {intercept:.2f}+{slope:.2f}*x')

The linear regression equation is y = -124.13+4.41*x


### Prediction

In [27]:
model.predict([[90]])

array([272.36333491])

### Using statsmodel

In [30]:
import statsmodels.api as sm

In [34]:
x=np.array([60,62,67,70,71,72,75,78])
y=np.array([140,155,159,179,192,200,212,215])

x_withconstant = sm.add_constant(x)

model = sm.OLS(y,x_withconstant).fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.931
Method:                 Least Squares   F-statistic:                     95.84
Date:                Tue, 03 Feb 2026   Prob (F-statistic):           6.54e-05
Time:                        15:16:30   Log-Likelihood:                -26.115
No. Observations:                   8   AIC:                             56.23
Df Residuals:                       6   BIC:                             56.39
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -124.1312     31.326     -3.963      0.0

In [41]:
import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv("olympic100m.csv")

In [52]:
x1 = df[['year']]
y1 = df['time']

In [53]:
model1 = LinearRegression()

In [54]:
model1.fit(x1,y1)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [55]:
#slope
print(model1.coef_[0])
#intercept
print(model1.intercept_)

-0.01288516743125567
35.554833461527906


In [56]:
slope = model.coef_[0]
intercept = model.intercept_

In [57]:
print(f'The linear regression equation is y = {intercept:.2f}+{slope:.2f}*x')

The linear regression equation is y = 3.46+0.30*x


In [59]:
model1.predict([[2026]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.44948425])

### Polynomial regression
- it is used when the data is not linear but follows curved patttern



In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [6]:
# load dataset
df = pd.read_csv("Iris(1).csv")

In [7]:
x = df[['SepalLengthCm']]
y = df['PetalLengthCm']
print(x.shape)
print(y.shape)


(150, 1)
(150,)


### create polynomial features

In [9]:
poly = PolynomialFeatures(degree=2)
x_poly = poly.fit_transform(x)
model = LinearRegression()
model.fit(x_poly,y)
print(model.coef_) 
print(model.intercept_)

[ 0.          5.3854114  -0.29537127]
-17.42358580663512


### Steps to install agentic ai

```
STEP 1 - INSTALL OLLAMA
STEP 2 - INSTALL CLAUDE
STEP 3 - INSTALL OLLAMA AND CLAUDE IN VS CODE
STEP 4 - USE OLLAMA MINIMAX 2.5 CLAUDE - CLOUD MODEL
STEP 5 - INSTALL CODEX